apiVersion: v1
appVersion: "1.0"
description: A Helm chart for NBoost
name: nboost
fullname: nboost
serviceAccountName: nboost
version: 0.0.2
icon: https://raw.githubusercontent.com/koursaros-ai/nboost/master/.github/banner.svg?sanitize=true